#+ endpoint: https://api.labs.kadaster.nl/datasets/bgt-high3/Open-Areaaldata/services/Open-Areaaldata/sparql
#+ summary: Wegdelen uit een areaalviewer testset van Noord-Holland
#+ tags: 
#+   - AreaaldataWegdelen

prefix ad: <http://otl.noord-holland.nl/areaaldata/def/objecttype/>
PREFIX adprop: <http://otl.noord-holland.nl/areaaldata/def/eigenschap/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
prefix data: <http://connecteddata.nl/id/data/> 

select * where { 
	?s a ad:wegdeel ;
    		adprop:FUNCTIE ?f ;
		adprop:GEBRUIKSFUNCTIE ?gf ;
		adprop:VERHARDINGSCATEGORIE ?vh .
    ?s geo:hasGeometry/geo:asWKT ?geo.
} limit 1000
